name: test-timeout

on:
  workflow_dispatch:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
    - name: echo job1
      run: |
        sleep 120
        echo "job1"
    timeout-minutes: 2
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
    - name: echo job2
      run: | 
        echo "job2"
    timeout-minutes: 1
  job3:
    name: job3
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: echo job2
      run: |
        sleep 120 
        echo "job3"
    timeout-minutes: 1